name: Create Release from Version Info

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read version
        id: version
        run: echo "::set-output name=tag::$(cat version.txt)"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: "Release ${{ steps.version.outputs.tag }}"
          body: "New release ${{ steps.version.outputs.tag }} with the latest executable."
          draft: false
          prerelease: false


